### ISSUE TITLE
Clarifying README's description of behaviour?

### ISSUE THREAD

**Issue by claremacrae** [benhughes/obsidian-link-exploder#1]
Hello! You asked for feedback - and I was keen to see what this did before installing it.

This is a very small comment but I hope it may help others have the confidence to try it out...

In the README, the sentence 'converts the current note into a canvas' makes it sounds like it modifies the current note.
Does it really change the current note, or create a new file with info from the note?
If the latter, could you perhaps add a note about what the new file will be called please?

**Comment by benhughes** [comment]
Hi there, yeah sorry that’s not too clear.

It doesn’t touch the note at all and just reads it and creates a new canvas file (with the same name in the root of your vault) so performing the action on <note-name>.md will create a new file called <note-name>.canvas.

I’ll update the readme and make it clearer. Thanks for your feedback.

**Comment by claremacrae** [comment]
Hi Ben, that makes perfect sense. Thank you very much. I'm looking forward to trying it out!

**Comment by benhughes** [comment]
Have updated the Readme, hopefully it's clearer now. Thanks for the feedback

**Comment by claremacrae** [comment]
That’s great. It’s really clear. Thank you!
