### ISSUE TITLE
[Feature Request] Create In Folder Setting

### ISSUE THREAD

**Issue by Desymoo** [benhughes/obsidian-link-exploder#11]
Hello! 

Just wanted to make a small request for a setting that would allow the canvas to be created in the same folder as the note it's being created from instead of the root folder. I'm currently moving it into the proper folder using a script, so not a huge deal, but I figured it might be a helpful setting for others as well.

Thank you for the wonderful plugin!

**Comment by benhughes** [comment]
Feature has been released. Thanks for the request
