### ISSUE TITLE
backlinks exploder (feature request)

### ISSUE THREAD

**Issue by 1chevre** [benhughes/obsidian-link-exploder#2]
Hello,

Congrats this is a very nice plugin!
I wanted to know if it may be possible instead of using the outgoing links we could choose to embed the backlinks of the note?

Thank you!

**Comment by benhughes** [comment]
Hi there, yeah that's on my todo list. So will hopefully add the feature soon.

**Comment by benhughes** [comment]
This should be live with 0.2.0, make sure you update with BRAT

 let me know if you find any issues.

**Comment by 1chevre** [comment]
Thank you this is great!

What do you think about the idea of implemeting some commands like those for the graph local view?
![image](https://user-images.githubusercontent.com/88283052/210585687-c53ebaae-155d-4f1f-b573-84cb1250e119.png)

**Comment by benhughes** [comment]
Yeah was thinking about it, but wanted to make it as simple as possible. Will look at doing things like this once it's in the community directory and see if people are using it.
