### ISSUE TITLE
[FR] Mobile Support

### ISSUE THREAD

**Issue by stef-rausch** [benhughes/obsidian-link-exploder#9]
Do you plan to support the mobile app too?

Use case: A quick and viable alternative for Excalibrain, for which one needs to install Excalidraw and Dataview additionally. It would allow for a fast, stable, on-the-go visual representation of relationships.

**Comment by benhughes** [comment]
Thanks for suggesting, I've updated the config to allow it run on mobile in 0.2.5

When I originally developed the plugin canvas wasn't avaialble on mobile so it was still turned off from then. Can you check it's working for you?

**Comment by stef-rausch** [comment]
Works like a charm, Ben -- thank you!
